### ISSUE TITLE
Update bundled Prettier version?

### ISSUE THREAD

**Issue by lydell** [duailibe/atom-miniprettier#1]
1.12.1 → 1.13.5

Alternatively, have you thought about supporting _global_ Prettier?

1. Local
2. Global
3. Bundled

That way you wouldn’t have to keep up with new Prettier versions that often (people can just upgrade their global Prettier). Just a thought.

I install Prettier locally in all my projects, but for quick throw-away tests and whatnot it’s nice not having to install anything but still have my miniprettier keyboard shortcut work. On the other hand, for such cases it doesn’t really matter if I use the latest-and-greatest Prettier or not.

**Comment by duailibe** [comment]
Hey @lydell, happy to know you're using this :)

I was going to update but got distracted, so thanks for the reminder.

I think it's a valid approach, I don't usually install anything globally so I didn't consider that, but that sounds reasonable. I might even start doing that myself

**Comment by duailibe** [comment]
Released 1.0
